(import chicken scheme foreign foreigners)
(require openvg)
(require cvpi)
(let ((settings (cvpi_egl_settings_create)))
  (if (zero? settings)
      (printf "Is zero~N")
      (printf "Is not zero~N"))
  (free settings))

(let ((destroyer #f))
  (->> (vgCreateImage width height destroyer) (doSomethingWithIt) (force destroyer)))
(let ((destroyer #f))
  ((force destroyer) (doSomethingWithIt (vgCreateImage width height destroyer))))

(with-promises ((destroyImage1 image1 (createImage))
		(destroyImage2 image2 (createImage))
		(destroyImage3 image3))
	       (modImge image1)
	       (set!-values (destroyImage3 image3) (createImage))
	       (force destroyImage1))
