# This file is part of CVPI.
# 
# Copyright (C) 2015 Devin Homan
# 
# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

env = Environment(CCFLAGS='-O3 -std=gnu99 -DCVPI_ASSEMBLY=1 -DCVPI_CAREFUL=1 -DHAVE_BCM_HOST=1 -DCVPI_LOGGING=0 -DCVPI_TIME=0',
                  CPPPATH= ['.', '../include', '/opt/vc/include/', '/opt/vc/include/EGL/', 
                            '/opt/vc/include/interface/vmcs_host/linux/', '/opt/vc/include/interface/vcos/pthreads/'])

env.Program('cvpi_tests', ['cvpi_egl_config_tests.c','cvpi_egl_surface_functions.c',
                           'cvpi_image_tests.c','cvpi_tests.c'], 
            LIBS=['m', 'EGL', 'GLESv2', 'bcm_host', 'libcvpi', 'pthread'], LIBPATH=['/opt/vc/lib', '..'])

env.Program('khr_lock_surface_test', ['khr_lock_surface_test.c'], 
            LIBS=['m', 'EGL', 'GLESv2', 'bcm_host', 'libcvpi'], LIBPATH=['/opt/vc/lib', '..'])

env.Program('cvpi_sample_motion_detection', ['cvpi_egl_surface_functions.c','cvpi_camera_setup.c', 'cvpi_sample_motion_detection.c'], 
            LIBS=['m', 'EGL', 'GLESv2', 'bcm_host', 'libcvpi', 'pthread', 'rt'], LIBPATH=['/opt/vc/lib', '..', '.'])

env.Program('cvpi_sample_yuv2bmp', ['cvpi_sample_yuv2bmp.c'], 
            LIBS=['m', 'EGL', 'GLESv2', 'bcm_host', 'libcvpi'], LIBPATH=['/opt/vc/lib', '..', '.'])
