#!/bin/sh

# This file is part of CVPI.
#
#  Copyright 2017 Devin Homan
# 
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# using a makefile to select and run tests

# allow the user to select goals using globbing or regular-expressions

# options not used by make: -acDEFgGhHJmMPQuUVxyYzZ, 

# relevant options used by grep: unused by make: -EFGPxy  used by make: fivw
# y can be used in place of i

# not using grep's Generic Program Information, General Output Control, 
# Ouput Line Prefix Control, Context Line Control, Context Line Control, or Other options

# only using grep's Matcher Selection and Matching Control Options

# options unused by make or grep: acDghHJKmMNQTuUVXYzZ
# use -v for grep -v : invert match, no need to output make's version
# use -u for grep -w : word-regexp
# use -h for grep -f : pattern file
# use -g for grep -e : pattern

# pass other options to grep and make
#       Make options                           Grep options, make-grep options
getopts bmBC:def:iI:j:kl:Lno:O:pqrRsStwW:NXT:K:EFGPxyvuh:g:JZVQ

# -N and -X options used by FreeBSD make
# -Z --decompress and -J --bz2decompress used by FreeBSD grep

# -T used by NetBSD bmake, -V not being used (used for querying variables)

# OpenSolaris make
# --dd
# --DD
# -K statefile
# -P prints dependencies, option used by grep, 

# tmake tmake.sourceforge.net
# --template=type
# --lib
# --unix
# --win32

# grep long options
# --extended-regexp
# --fixed-strings
# --basic-regexp
# --perl-regexp
# --regexp=PATTERN
# --file=FILE
# --ignore-case
# --invert-match
# --word-regexp
# --line-regexp

# make long options
# --always-make
# --directory=dir
# --debug[=FLAGS]
# --environment-overrides
# --file=file
# --makefile=FILE
# --ignore-errors
# --include-dir=dir
# --jobs[=jobs]
# --keep-going
# --load-average[=load]
# --check-symlink-times
# --just-print
# --dry-run
# --recon
# --old-file=file
# --assume-old=file
# --output-sync[=type]
# --print-data-base
# --question
# --no-builtin-rules
# --no-builtin-variables
# --silent
# --quiet
# --no-keep-going
# --stop
# --touch
# --trace
# --print-directory
# --no-print-directory
# --what-if=file
# --new-file=file
# --assume-new=file
# --warn-undefined-variables
# 

# make-grep options
# -V --version :: Output the version number of make-grep and exit.
# --help :: Output a usage message and exit
# -Q --quiet :: Do not write anything to standard output

$OPTIND # name and index of next argument
$OPTARG # options given by user
